name: Deploy to Cloudflare Pages

on:
  push:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.DEPLOY_PAT }}
      - name: Generate PDF document
        uses: hspaans/latexmk-action@v2.1.0
        with:
          format: pdf
          filename: resume/main.tex
          options: -pdf -jobname=resume/Dev_Singh_resume
      - name: Copy artifact
        run: mv resume/Dev_Singh_resume.pdf public/
      - name: Build
        run: yarn && yarn build:wrangler
      - name: Deploy
        run: yarn run deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: f81080552fd4a731cc7942c29b33df15
